version: 2
jobs:
    build:
      working_directory: ~/leonard-nimoy
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
          - checkout
          - restore_cache:
              key: grails
          - run:
              name: compile-dependencies
              command: ./grailsw compile --refresh-dependencies
          - run:
              name: clean
              command: ./grailsw clean
          - save_cache:
              key: grails
              paths:
                - ~/.grails/wrapper/2.5.5
    test:
      working_directory: ~/leonard-nimoy
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
          - run:
              name: codenarc
              command: ./grailsw codenarc
          - run:
              name: test
              command: ./grailsw test-app -coverage
          - run:
              name: stats
              command: ./grailsw stats
          - store_artifacts:
              path: target/test-reports/cobertura
              prefix: coverage
          - store_artifacts:
              path: target/CodeNarcReport.html
              prefix: codenarc
          - store_artifacts:
              path: target/test-reports/html/*
              prefix: test
    compile:
      working_directory: ~/leonard-nimoy
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
          - run:
              name: make war
              command: ./grailsw prod war

workflows:
  version: 2
  build_and_test_and_compile:
    jobs:
      - build
      - test
      - compile